package enums;

public enum CodeMoedas {

    USD("Dólar Americano"),
    AED("Dirham dos Emirados Árabes Unidos"),
    AFN("Afegane Afegão"),
    ALL("Lek Albanês"),
    AMD("Dram Armênio"),
    ANG("Florim das Antilhas Holandesas"),
    AOA("Kwanza Angolano"),
    ARS("Peso Argentino"),
    AUD("Dólar Australiano"),
    AWG("Florim de Aruba"),
    AZN("Manat Azerbaijano"),
    BAM("Marco Conversível da Bósnia e Herzegovina"),
    BBD("Dólar de Barbados"),
    BDT("Taka de Bangladesh"),
    BGN("Lev Búlgaro"),
    BHD("Dinar do Bahrein"),
    BIF("Franco Burundês"),
    BMD("Dólar das Bermudas"),
    BND("Dólar de Brunei"),
    BOB("Boliviano"),
    BRL("Real Brasileiro"),
    BSD("Dólar das Bahamas"),
    BTN("Ngultrum do Butão"),
    BWP("Pula de Botswana"),
    BYN("Rublo Bielorrusso"),
    BZD("Dólar de Belize"),
    CAD("Dólar Canadense"),
    CDF("Franco Congolês"),
    CHF("Franco Suíço"),
    CLP("Peso Chileno"),
    CNY("Yuan Chinês"),
    COP("Peso Colombiano"),
    CRC("Colón Costarriquenho"),
    CUP("Peso Cubano"),
    CVE("Escudo Cabo-Verdiano"),
    CZK("Coroa Tcheca"),
    DJF("Franco do Djibuti"),
    DKK("Coroa Dinamarquesa"),
    DOP("Peso Dominicano"),
    DZD("Dinar Argelino"),
    EGP("Libra Egípcia"),
    ERN("Nakfa Eritreia"),
    ETB("Birr Etíope"),
    EUR("Euro"),
    FJD("Dólar de Fiji"),
    FKP("Libra das Ilhas Malvinas"),
    FOK("Coroa das Ilhas Faroe"),
    GBP("Libra Esterlina"),
    GEL("Lari Georgiano"),
    GGP("Libra de Guernsey"),
    GHS("Cedi Ganês"),
    GIP("Libra de Gibraltar"),
    GMD("Dalasi da Gâmbia"),
    GNF("Franco Guineense"),
    GTQ("Quetzal da Guatemala"),
    GYD("Dólar da Guiana"),
    HKD("Dólar de Hong Kong"),
    HNL("Lempira Hondurenha"),
    HRK("Kuna Croata"),
    HTG("Gourde Haitiano"),
    HUF("Forint Húngaro"),
    IDR("Rupia Indonésia"),
    ILS("Novo Shekel Israelense"),
    IMP("Libra da Ilha de Man"),
    INR("Rupia Indiana"),
    IQD("Dinar Iraquiano"),
    IRR("Rial Iraniano"),
    ISK("Coroa Islandesa"),
    JEP("Libra de Jersey"),
    JMD("Dólar Jamaicano"),
    JOD("Dinar Jordaniano"),
    JPY("Iene Japonês"),
    KES("Xelim Queniano"),
    KGS("Som Quirguiz"),
    KHR("Riel Cambojano"),
    KID("Dólar de Kiribati"),
    KMF("Franco Comorense"),
    KRW("Won Sul-Coreano"),
    KWD("Dinar Kuwaitiano"),
    KYD("Dólar das Ilhas Cayman"),
    KZT("Tenge Cazaque"),
    LAK("Kip Laosiano"),
    LBP("Libra Libanesa"),
    LKR("Rupia do Sri Lanka"),
    LRD("Dólar Liberiano"),
    LSL("Loti do Lesoto"),
    LYD("Dinar Líbio"),
    MAD("Dirham Marroquino"),
    MDL("Leu Moldavo"),
    MGA("Ariary Malgaxe"),
    MKD("Dinar Macedônio"),
    MMK("Kyat de Mianmar"),
    MNT("Tugrik Mongol"),
    MOP("Pataca de Macau"),
    MRU("Ouguiya Mauritana"),
    MUR("Rupia Mauriciana"),
    MVR("Rufiyaa Maldiva"),
    MWK("Kwacha Malauiano"),
    MXN("Peso Mexicano"),
    MYR("Ringgit Malaio"),
    MZN("Metical Moçambicano"),
    NAD("Dólar Namibiano"),
    NGN("Naira Nigeriana"),
    NIO("Córdoba Nicaraguense"),
    NOK("Coroa Norueguesa"),
    NPR("Rupia Nepalesa"),
    NZD("Dólar Neozelandês"),
    OMR("Rial Omanense"),
    PAB("Balboa Panamenho"),
    PEN("Sol Peruano"),
    PGK("Kina Papua-Nova-Guineense"),
    PHP("Peso Filipino"),
    PKR("Rupia Paquistanesa"),
    PLN("Zloty Polonês"),
    PYG("Guarani Paraguaio"),
    QAR("Rial Catariano"),
    RON("Leu Romeno"),
    RSD("Dinar Sérvio"),
    RUB("Rublo Russo"),
    RWF("Franco Ruandês"),
    SAR("Riyal Saudita"),
    SBD("Dólar das Ilhas Salomão"),
    SCR("Rupia de Seychelles"),
    SDG("Libra Sudanesa"),
    SEK("Coroa Sueca"),
    SGD("Dólar de Singapura"),
    SHP("Libra de Santa Helena"),
    SLE("Leone de Serra Leoa"),
    SLL("Leone de Serra Leoa (antigo)"),
    SOS("Xelim Somali"),
    SRD("Dólar do Suriname"),
    SSP("Libra Sul-Sudanesa"),
    STN("Dobra de São Tomé e Príncipe"),
    SYP("Libra Síria"),
    SZL("Lilangeni Suazi"),
    THB("Baht Tailandês"),
    TJS("Somoni Tadjique"),
    TMT("Manat Turcomeno"),
    TND("Dinar Tunisiano"),
    TOP("Paʻanga de Tonga"),
    TRY("Lira Turca"),
    TTD("Dólar de Trinidad e Tobago"),
    TVD("Dólar de Tuvalu"),
    TWD("Novo Dólar Taiwanês"),
    TZS("Xelim Tanzaniano"),
    UAH("Hryvnia Ucraniana"),
    UGX("Xelim Ugandês"),
    UYU("Peso Uruguaio"),
    UZS("Som Uzbeque"),
    VES("Bolívar Venezuelano"),
    VND("Dong Vietnamita"),
    VUV("Vatu de Vanuatu"),
    WST("Tala Samoano"),
    XAF("Franco CFA BEAC"),
    XCD("Dólar do Caribe Oriental"),
    XCG("Guilder Caribenho"),
    XDR("Direitos Especiais de Saque"),
    XOF("Franco CFA BCEAO"),
    XPF("Franco CFP"),
    YER("Rial Iemenita"),
    ZAR("Rand Sul-Africano"),
    ZMW("Kwacha Zambiano"),
    ZWL("Dólar Zimbabuano");


    private final String descricao;

    CodeMoedas(String s) {

        this.descricao = s;
    }

    public String getDescricao() {
        return descricao;
    }


}